apiVersion: apps/v1
kind: Deployment
metadata:
  name: waste-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waste-backend
  template:
    metadata:
      labels:
        app: waste-backend
    spec:
      containers:
        - name: waste-backend
          image: waste-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8001
          env:
            - name: SPLUNK_HEC_HOST
              value: "192.168.49.1"
            - name: SPLUNK_HEC_PORT
              value: "8088"
            - name: SPLUNK_HEC_TOKEN
              value: "REPLACE_WITH_YOUR_SPLUNK_HEC_TOKEN"
---
apiVersion: v1
kind: Service
metadata:
  name: waste-backend-svc
spec:
  selector:
    app: waste-backend
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001
