apiVersion: v1
kind: Secret
metadata:
  name: waste-backend-secret
  namespace: waste-mlops
  labels:
    app.kubernetes.io/name: waste-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: waste-mlops
type: Opaque
stringData:
  DATABASE_URL: postgresql://waste_user:REPLACE_WITH_YOUR_POSTGRES_PASSWORD@postgres:5432/waste_db
