apiVersion: apps/v1
kind: Deployment
metadata:
  name: waste-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waste-backend
  template:
    metadata:
      labels:
        app: waste-backend
    spec:
      containers:
        - name: waste-backend
          image: waste-backend:latest
          imagePullPolicy: Never   # <- This tells K8s to use local image

          ports:
            - containerPort: 8001
          env:
            - name: SPLUNK_HEC_HOST
              value: "192.168.49.1"
            - name: SPLUNK_HEC_PORT
              value: "8088"
            - name: SPLUNK_HEC_TOKEN
              value: "3e9bd471-4702-4b48-b35e-699d1f7f5883"