apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: waste-mlops
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: waste-mlops
type: Opaque
stringData:
  POSTGRES_PASSWORD: REPLACE_WITH_YOUR_POSTGRES_PASSWORD
